### ISSUE TITLE
Mod dir not found

### ISSUE THREAD

**Issue by SoraDragon** [thundrio-kh/khpc-modsmanager-bridge#3]
Hello,
I've been trying to setup the bridge, but I can't get it to work. Everytime it tells me that "Mod dir not found". I'm certain that my paths are correct so I don't know what he is unable to find. Is there something else you have to do with the openkh except extracting it to work? 
![grafik](https://user-images.githubusercontent.com/15896743/138665147-e6446ac1-8441-49d0-aa5e-1c669d2667dc.png)

**Comment by snelson3** [comment]
I believe I fixed this in a recent version so I'm closing this. If you still need help please reopen.
